name: Fetch NAV Data

permissions:
  contents: write

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 5 * * 4'  # 11 AM BD time = 5 AM UTC on Thursday
  workflow_dispatch:

jobs:
  update-nav:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # <— allow pushes using GITHUB_TOKEN

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Download dependencies
        run: go mod download

      - name: Run Go script
        run: go run main.go

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet updated-nav.txt; then
            git add updated-nav.txt
            git commit -m "Update NAV data [auto]"
            git push
          else
            echo "No NAV changes detected"
          fi
